# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x12\x07user.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"#\n\x15GetUserProfileRequest\x12\n\n\x02id\x18\x01 \x01(\t\"H\n\x13RegisterUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"=\n\x17\x41uthenticateUserRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"+\n\x0c\x41uthResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\n\n\x02id\x18\x02 \x01(\t\"\xee\x01\n\x13UserProfileResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x0f\n\x07surname\x18\x05 \x01(\t\x12\x15\n\rdate_of_birth\x18\x06 \x01(\t\x12\x14\n\x0cphone_number\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"u\n\x18UpdateUserProfileRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07surname\x18\x02 \x01(\t\x12\x15\n\rdate_of_birth\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x14\n\x0cphone_number\x18\x05 \x01(\t\".\n\rErrorResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t2\xd4\x02\n\x0bUserService\x12L\n\x0cRegisterUser\x12\x1c.user.v1.RegisterUserRequest\x1a\x1c.user.v1.UserProfileResponse\"\x00\x12M\n\x10\x41uthenticateUser\x12 .user.v1.AuthenticateUserRequest\x1a\x15.user.v1.AuthResponse\"\x00\x12P\n\x0eGetUserProfile\x12\x1e.user.v1.GetUserProfileRequest\x1a\x1c.user.v1.UserProfileResponse\"\x00\x12V\n\x11UpdateUserProfile\x12!.user.v1.UpdateUserProfileRequest\x1a\x1c.user.v1.UserProfileResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERPROFILEREQUEST']._serialized_start=59
  _globals['_GETUSERPROFILEREQUEST']._serialized_end=94
  _globals['_REGISTERUSERREQUEST']._serialized_start=96
  _globals['_REGISTERUSERREQUEST']._serialized_end=168
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_start=170
  _globals['_AUTHENTICATEUSERREQUEST']._serialized_end=231
  _globals['_AUTHRESPONSE']._serialized_start=233
  _globals['_AUTHRESPONSE']._serialized_end=276
  _globals['_USERPROFILERESPONSE']._serialized_start=279
  _globals['_USERPROFILERESPONSE']._serialized_end=517
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_start=519
  _globals['_UPDATEUSERPROFILEREQUEST']._serialized_end=636
  _globals['_ERRORRESPONSE']._serialized_start=638
  _globals['_ERRORRESPONSE']._serialized_end=684
  _globals['_USERSERVICE']._serialized_start=687
  _globals['_USERSERVICE']._serialized_end=1027
# @@protoc_insertion_point(module_scope)
